universal:
  - $A_SOCIETY_AGENTS
  - $A_SOCIETY_INDEX
roles:
  owner:
    - $A_SOCIETY_ADOCS_DESIGN
    - $A_SOCIETY_OWNER_ROLE
    - $A_SOCIETY_VISION
    - $A_SOCIETY_STRUCTURE
    - $A_SOCIETY_ARCHITECTURE
    - $A_SOCIETY_PRINCIPLES
    - $A_SOCIETY_LOG
    - $A_SOCIETY_WORKFLOW
    - $A_SOCIETY_OWNERSHIP
  curator:
    - $A_SOCIETY_ADOCS_DESIGN
    - $A_SOCIETY_CURATOR_ROLE
    - $A_SOCIETY_VISION
    - $A_SOCIETY_STRUCTURE
    - $A_SOCIETY_PRINCIPLES
    - $A_SOCIETY_AGENT_DOCS_GUIDE
  technical-architect:
    - $A_SOCIETY_TECHNICAL_ARCHITECT_ROLE
    - $A_SOCIETY_VISION
    - $A_SOCIETY_STRUCTURE
    - $A_SOCIETY_ARCHITECTURE
    - $A_SOCIETY_PRINCIPLES
  framework-services-developer:
    - $A_SOCIETY_FRAMEWORK_SERVICES_DEVELOPER_ROLE
    - $A_SOCIETY_ARCHITECTURE
  orchestration-developer:
    - $A_SOCIETY_ORCHESTRATION_DEVELOPER_ROLE
    - $A_SOCIETY_ARCHITECTURE
